#SITE CONFIGURATION

title: Nick Montoya
description: Percussionist Drummer Musicologist
repository: "nickmontoyamusik/music-portfolio"
baseurl: 
url: "https://nickmontoyamusik.github.io/music-portfolio/"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Nick Montoya
  links:
    - https://www.facebook.com/andrewstiefel
    - https://twitter.com/andrewstiefel
    - https://www.instagram.com/andrewstiefel
    - https://www.youtube.com/user/andrewstiefel
    - https://www.linkedin.com/in/andrewstiefel
    - https://github.com/andrewstiefel
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: nbm23b@fsu.edu
github_username: nickmontoyamusik
instagram_username: nick.montoya.musik
facebook_username: Nick Montoya
linkedin_username: Nick Montoya

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
